[book]
authors = ["robopandas"]
language = "en"
multilingual = false
src = "src"
title = "Seattle Solvers Docs"

[output.html.code.hidelines]
java = "# "
kt = "# "

[output.html]
mathjax-support = true
site-url = "/docs/"
git-repository-url = "https://github.com/FTC-23511/docs/tree/master"
edit-url-template = "https://github.com/FTC-23511/docs/tree/master/{path}"
